language: python
python:
  - 2.7
  - 3.3
install:
  - pip install 'Flask>=0.10' mohawk --use-mirrors
  - python setup.py install
script: nosetests tests
notifications:
  email:
    recipients:
      - marselester@ya.ru
    on_success: change
    on_failure: change
